### PR TITLE
Handle https requests

### PR DESCRIPTION
**Pull request by alexdemidov**
Hi.

I prepared pull-request with support of HTTPS handling. Could you check it and merge with master branch, please?

### CODE REVIEW

**Comment by gunnaraasen** [comment]
👍 @alexdemidov Can you please sign the [CLA](https://influxdata.com/community/cla/)?

**Comment by alexdemidov** [comment]
@gunnaraasen I have signed CLA.

**Comment by joelegasse** [comment]
Some changes I'd like to see:

- Remove the `enabled` option, if there is a certificate file set, it will use TLS, if not, plain HTTP over TCP will be used.
- Use [tls.NewListener](https://golang.org/pkg/crypto/tls/#NewListener) rather than two separate listen calls. It means that the only conditional element is the upgrade to TLS, and not the TCP listen portion.
- Change the config variable to `tls-combined-pem` to indicate that we're requiring a single PEM file with both the key and the certificate chain included.

**Comment by alexdemidov** [comment]
@joelegasse Thanks for you comments. I have applied changes. Could you have a look, please?

**Comment by alexdemidov** [comment]
@joelegasse I renamed tls-combined-pem config option to ssl-combined-pem.

**Comment by joelegasse** [comment]
@alexdemidov Much cleaner diff, I like it. :-)

**Comment by alexdemidov** [comment]
Thanks.

**Pull request merged**
